#!/usr/bin/env bash

if [ "$1" = 'display-message' ]; then
  exit 0
fi

shift
while [ "$#" -gt 0 ]; do
  case "$1" in
    -e)
      export "$2"
      shift 2
      ;;
    -w | -h)
      shift 2
      ;;
    -E)
      shift
      ;;
    *)
      shift
      ;;
  esac
done

if [ "${SIDO_E2E_MODE:-}" = 'fail' ]; then
  exit 42
fi

stat -c '%a' \
  "$(dirname "$SIDO_FIFO")" \
  "$SIDO_FIFO" \
  "$SIDO_PROMPT" > "$SIDO_E2E_MODE_LOG"
printf '%s\n' 'fake-password' > "$SIDO_FIFO"
